[package]
name = "hsakmt-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2"
amdgpu-drm-sys = { path = "../amdgpu-drm-sys" }
xf86drm-sys = { path = "../xf86drm-sys" }
numa-sys = { path = "../numa-sys" }
#utilities = { path = "../utilities" }
