/* automatically generated by rust-bindgen 0.70.1 */

pub const NUMAIF_H: u32 = 1;
pub const MPOL_DEFAULT: u32 = 0;
pub const MPOL_PREFERRED: u32 = 1;
pub const MPOL_BIND: u32 = 2;
pub const MPOL_INTERLEAVE: u32 = 3;
pub const MPOL_LOCAL: u32 = 4;
pub const MPOL_MAX: u32 = 5;
pub const MPOL_F_NODE: u32 = 1;
pub const MPOL_F_ADDR: u32 = 2;
pub const MPOL_F_MEMS_ALLOWED: u32 = 4;
pub const MPOL_MF_STRICT: u32 = 1;
pub const MPOL_MF_MOVE: u32 = 2;
pub const MPOL_MF_MOVE_ALL: u32 = 4;
extern "C" {
    pub fn get_mempolicy(
        mode: *mut ::std::os::raw::c_int,
        nmask: *mut ::std::os::raw::c_ulong,
        maxnode: ::std::os::raw::c_ulong,
        addr: *mut ::std::os::raw::c_void,
        flags: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn mbind(
        start: *mut ::std::os::raw::c_void,
        len: ::std::os::raw::c_ulong,
        mode: ::std::os::raw::c_int,
        nmask: *const ::std::os::raw::c_ulong,
        maxnode: ::std::os::raw::c_ulong,
        flags: ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn set_mempolicy(
        mode: ::std::os::raw::c_int,
        nmask: *const ::std::os::raw::c_ulong,
        maxnode: ::std::os::raw::c_ulong,
    ) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn migrate_pages(
        pid: ::std::os::raw::c_int,
        maxnode: ::std::os::raw::c_ulong,
        frommask: *const ::std::os::raw::c_ulong,
        tomask: *const ::std::os::raw::c_ulong,
    ) -> ::std::os::raw::c_long;
}
extern "C" {
    pub fn move_pages(
        pid: ::std::os::raw::c_int,
        count: ::std::os::raw::c_ulong,
        pages: *mut *mut ::std::os::raw::c_void,
        nodes: *const ::std::os::raw::c_int,
        status: *mut ::std::os::raw::c_int,
        flags: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_long;
}
